import * as colors from './colors'

export const light = {
  ...colors,
  primary: colors.primary6,
  text: colors.grey9,
  link: colors.blue,
  footerText: colors.grayDark,
  sidebarBg: colors.grey2,
  sidebarText: colors.dark,
  sidebarHighlight: null,
  sidebarBorder: colors.grayLight,
  background: colors.white,
  border: colors.grayLight,
  theadColor: colors.gray,
  theadBg: colors.grey2,
  tableColor: colors.dark,
  tooltipBg: colors.dark,
  tooltipColor: colors.grey2,
  codeBg: colors.grey2,
  codeColor: colors.gray,
  preBg: colors.grey2,
  blockquoteBg: colors.grey2,
  blockquoteBorder: colors.grayLight,
  blockquoteColor: colors.gray,
  propsText: colors.gray,
  propsBg: colors.grayUltraLight,
}

export const dark = {
  ...colors,
  primary: colors.skyBlue,
  text: colors.grey2,
  link: colors.skyBlue,
  footerText: colors.grayLight,
  sidebarBg: colors.dark,
  sidebarText: colors.grayLight,
  sidebarHighlight: null,
  sidebarBorder: colors.grayDark,
  background: colors.grayExtraDark,
  border: colors.grayDark,
  theadColor: colors.gray,
  theadBg: colors.grayDark,
  tableColor: colors.grey2,
  tooltipBg: colors.dark,
  tooltipColor: colors.grey2,
  codeBg: colors.gray,
  codeColor: colors.grey2,
  preBg: colors.grayDark,
  blockquoteBg: colors.grayDark,
  blockquoteBorder: colors.gray,
  blockquoteColor: colors.gray,
  propsText: colors.grayLight,
  propsBg: colors.dark,
}
